language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-19mode

gemfile:
 - Gemfile
 - Gemfile.fluentd.lt.0.10.43

branches:
  only:
    - master

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: rbx-19mode
